# Generated by Django 4.0.4 on 2022-05-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_attrib', '0002_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
